version: "3"
services:
  dbpostgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/serasadb\
    restart: always

    environment:
      - POSTGRES_USER=anderson
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dbserasa

    expose:
      - 5432
    networks:
      - backend

  apporder:
    build:
      context: ./order-api
    restart: always

    ports:
      - 5002:5002
    depends_on:
      - dbpostgres
    networks:
      - backend
    expose:
      - 5002

  appuser:
    # network_mode: host
    build:
      context: ./user-api
    restart: always
    ports:
      - 5000:5000 # host:container
    depends_on:
      - dbpostgres
    networks:
      - backend
    expose:
      - 5000

networks:
  backend: {}
